config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'import_excel', to: 'excel#import'
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :package, foreign_key: 'packageid'
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :packages, foreign_key: 'orderid'
end

app/models/package.rb
class Package < ApplicationRecord
	belongs_to :order, foreign_key: 'orderid'
	has_many :items, foreign_key: 'packageid'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/excel_controller.rb
class ExcelController < ApplicationController
  def import
    ExcelImport.read_excel_file
    flash[:notice] = "Database updated successfully from Excel file!"
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<%= form_tag '/import_excel', method: :post do %>
  <%= submit_tag "Update Database" %>
<% end %>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<%= link_to 'View Orders', orders_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestDiduenjoy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders</h1>

<% @orders.each do |order| %>
  <div>
    <p>Order ID: <%= order.orderid %> Order, Name: <%= order.odername %></p>
  </div>
<% end %>